version: '3'

services:
  postgres_local:
    image: postgres
    ports:
      - 5436:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  # mysql_local:
  #   image: mysql
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ~/apps/mysql:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=mysql
  #     - MYSQL_USER=mysql
  #     - MYSQL_PASSWORD=mysql
  #     - MYSQL_DATABASE=mysql